# Generated by Django 4.2.4 on 2023-08-15 18:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=150, verbose_name='Kategori Adı')),
                ('categorySlug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productCode', models.CharField(max_length=200, unique=True, verbose_name='Ürün Kodu')),
                ('productName', models.CharField(max_length=200, verbose_name='Ürün Adı')),
                ('productPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productStock', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('productImage', models.ImageField(upload_to='products', verbose_name='Ürün Resmi')),
                ('productInfo', models.TextField(verbose_name='Ürün Açıklaması')),
                ('isActive', models.BooleanField(default=False, verbose_name='Yayınla')),
                ('isHome', models.BooleanField(default=False, verbose_name='Anasayfada Göster')),
                ('productSlug', models.SlugField(blank=True, editable=False, unique=True)),
                ('productCategory', models.ManyToManyField(to='product.category', verbose_name='Kategoriler')),
            ],
        ),
    ]
