# Generated by Django 4.2.4 on 2023-08-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categoryName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='categorySlug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productCategory',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productCode',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productInfo',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productSlug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productStock',
            new_name='stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productImage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productName',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productPrice',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default=3, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=9),
            preserve_default=False,
        ),
    ]
