# Generated by Django 4.2.4 on 2023-09-20 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_image_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ProductImages',
        ),
    ]
